name:  Additional Matrix Configuration


on: 
 
 
 workflow_dispatch:

jobs:
    deploy:
      strategy:
        matrix:
          os: [ubuntu-latest, ubuntu-20.04, windows-latest]
          image: [nginx,alpine]
          exclude:
            - os: windows-latest
            - image: alpine
      runs-on: ${{matrix.os}}
      steps:
      - name: Logging into docker
        env:
          CONTAINER_REGISTRY: docker.io
          DOCKER_USER_NAME: machanikrishnakumar
        run: echo docker login --username=$DOCKER_USERNAME --password=${{ secrets.DOCKER_PASSWORD }}

      - name: pull the image
        run: echo docker pull ${{matrix.image}}

      - name: Run the image
        run: echo docker run ${{matrix.image}}
