name:  Additional Matrix Configuration


on: 
 
 
 push: # to run the job automatically

jobs:
    deploy:
      strategy:
        fail-fast: true # to stop the running jobs when the job is failure
        max-parallel: 2 # to control the count of jobs to run parallely.
        matrix:
          os: [ubuntu-latest, ubuntu-20.04, windows-latest]
          images: [nginx,tomcat]
          exclude: 
            - images: tomcat
              os: windows-latest
          include: # to add additional configuration to matrix strategy
            - images: alpine
              os: windows-latest
      runs-on: ${{matrix.os}}
      steps:
      - name: Logging into docker
        env:
          CONTAINER_REGISTRY: docker.io
          DOCKER_USER_NAME: machanikrishnakumar
        run: echo docker login --username=$DOCKER_USERNAME --password=${{ secrets.DOCKER_PASSWORD }}

      - name: pull the image
        run: echo docker pull ${{matrix.images}}

      - name: Run the image on ${{matrix.os}}
        run: echo docker run ${{matrix.images}}
