name: Accessing Workflow Context information

on: push

jobs:
  Context:
    runs-on: ubuntu-latest
    steps:
      - name: Dump Github context
        env: 
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "GITHUB_CONTEXT"
      - name: Dump Job Context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "JOB_CONTEXT"
      - name: Dump strategy commit
        env:
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
        run: echo "STRATEGY_CONTEXT"
      - name: Dump Secret Context
        env:
          SECRET_CONTEXT: ${{ toJson(secrets) }}
        run: echo "SECRET_CONTEXT"
      - name: Dump Matrix Context
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        run: echo "MATRIX CONTEXT"
      - name: Dump step context
        env:  
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "STEPS_CONTEXT"




