name: Accessing Workflow Context information

on: push

jobs:
  Context:
    runs-on: ubuntu-latest
    steps:
      - name: Dump Github context
        env: 
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "GITHUB_CONTEXT"
