name: Accessing Workflow Context information

on: push

jobs:
  Context:
    runs-on: ubuntu-latest
    steps:
      - name: Dump Github context
        env: 
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "GITHUB_CONTEXT"
      - name: Dump Job Context
        env:
          JOB_CONTEXT: ${{ toJson(job)}}
        run: echo "JOB_CONTEXT"
      - name: Dump strategy commit
        env:
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
        run: echo "STRATEGY_COMMIT"
        
