name: My Job workflow

on: 
#  workflow_dispatch:
   schedule:
     - cron: '*/1 * * * *'

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout repo
          uses: actions/checkout@v4
          
        - name: list all the files
          run: ls

        - name: Permission to shellscript
          run: chmod 777 script.sh

        - name: Executing shellscript
          run: ./script.sh
