name: My Job workflow

on: 
 workflow_dispatch:

concurrency:


jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout repo
          uses: actions/checkout@v4
          
        - name: list all the files
          run: ls

        - name: Permission to shellscript
          run: chmod 777 script.sh
          
    second_job:
      concurrency:
        group: second_job
        cancel-in-progress: true
      runs-on: ubuntu-latest
      steps:
         - name: Executing shellscript 
           run: ./script.sh
           sleep 120
