name: Matrix Configuration


on: 
 
 
 workflow_dispatch:

jobs:
    deploy:
      strategy:
        matrix:
          os: [ubuntu-latest, ubuntu 20.4]
          image: [machanikrishnakumar/tomcat]
      runs-on: ${{matrix.os}}
      steps:
          
          - name: docker login
            env:
              CONTAINER_REGISTRY: docker.io
              USER_NAME: machanikrishnakumar
            run: echo docker login --username=$DOCKER_USERNAME --password=${{ secrets.DOCKER_PASSWORD }}
          
          - name: pulling the image
            run: echo docker pull ${{matrix.image}}
          
          - name: Show the images
            run: echo docker images

          - name: Echo Docker details
            run: docker info
        
          - name: Run the Image
            run: docker run ${{matrix.image}}

    

