name: Matrix Configuration


on: 
 
 
 workflow_dispatch:

jobs:
    deploy:
      strategy:
        matrix:
          os: [ubuntu-latest, ubuntu 20.4]
      runs-on: ${{matrix.os}}
      steps:
      - name: Checkout repo
        uses: actions/checkout@v4
              
      - name: list all the files
        run: ls
    
      - name: Permission to shellscript
        run: chmod 777 script.sh
              
      - name: Executing shellscript 
        run: ./script.sh
           

    

