name: Shell script workflow

on: push

jobs:
    shellscript_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout repo
          uses: actions/checkout@v4

        - name: list all files
          run: ls -ltra

        - name: Executing shell script
          run:
             chmod +x shellscript.sh
             ./shellsctipt.sh