name: My shellscript

on: push

jobs:
    shellscript_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout repo
          uses: actions/checkout@v4

        - name: list all files
          run: ls -ltra

        - name: Executing shellscript
          run: 
            chmod +x shellscript.sh
            ./shellscript.sh

