name: Workflow with varibles

on: push

#using variables at step-level 
jobs:

   deploy:
      runs-on: ubuntu-latest
      steps:

      - name: Checkout repo
        uses: actions/checkout@v4  
      
      - name: Run an image
        env:
          CONTAINER_REGISTRY: docker.io
          DOCKER_USERNAME: machanikrishnakumar
          IMAGE_NAME: my-nginx
        run: docker run -d -p 8080:80 $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest




