name: Workflow with varibles

on: push

#using variables at step-level 
jobs:
       
   docker:
     runs-on: ubuntu-latest
     steps:

     - name: Checkout code
       uses: actions/checkout@v4

     - name: pulling an image
       run: docker pull nginx:latest

     - name: Login Docker
       env:
         DOCKER_USERNAME: machanikrishnakumar
       run: docker login --username=$DOCKER_USERNAME --password=${{ secrets.DOCKER_PASSWORD }} 


     - name: Pushing an image
       env:
         CONTAINER_REGISTRY: docker.io
         DOCKER_USERNAME: machanikrishnakumar
         IMAGE_NAME: my-nginx
       run: docker push $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest

     - name: sleep for few seconds
       run: sleep 10

   deploy:
      runs-on: ubuntu-latest
      steps:

      - name: Checkout repo
        uses: actions/checkout@v4  
      
      - name: Run an image
        env:
          CONTAINER_REGISTRY: docker.io
          DOCKER_USERNAME: machanikrishnakumar
          IMAGE_NAME: my-nginx
        run: docker run -d -p 8080:80 $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest




