name: Workflow with varibles

on: push

#using variables at step-level
jobs:
   docker:
     runs-on: ubuntu-latest
     steps:
     - name: Building an image
       env:
         CONTAINER_REGISTRY: docker.io
         DOCKER_USERNAME: machanikrishnakumar
         DOCKER_PASSWORD:
       run: docker build -t $CONTAINER_REGISTRY/$DOCKER_USERNAME/$DOCKER_PASSWORD

     - name: Login Docker
       env:
         DOCKER_USERNAME: machanikrishnakumar
         DOCKER_PASSWORD:
       run: docker login --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD

     - name: Pushing an image
       env:
         CONTAINER_REGISTRY: docker.io
         DOCKER_USERNAME: machanikrishnakumar
         IMAGE_NAME:
       run: docker push 

    deploy:




