name: Workflow with varibles

on: push

#using variables at step-level 
jobs:
       
   docker:
     runs-on: ubuntu-latest
     steps:

     - name: Checkout code
       uses: actions/checkout@v4

     - name: Login Docker
       env:
         DOCKER_USERNAME: machanikrishnakumar
       run: docker login --username=$DOCKER_USERNAME --password=${{ secrets.DOCKER_PASSWORD }} 

     - name: Building an image
       env:
         CONTAINER_REGISTRY: docker.io
         DOCKER_USERNAME: machanikrishnakumar
         IMAGE_NAME: nginx
       run: docker buildx build $IMAGE_NAME:latest -f ./Dockerfile 
    

     - name: Pushing an image
       env:
         CONTAINER_REGISTRY: docker.io
         DOCKER_USERNAME: machanikrishnakumar
         IMAGE_NAME: nginx
       run: docker push $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest

   deploy:
      runs-on: ubuntu-latest
      steps:
      - name: Run an image
        env:
          CONTAINER_REGISTRY: docker.io
          DOCKER_USERNAME: machanikrishnakumar
          IMAGE_NAME: nginx
        run: docker run -d -p 8080:80 $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest




